name: responsive_login_ui
description: Responsive SignUp & Login Screens

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^1.4.2
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  flutter_svg: ^1.1.5
  flutter_map_marker_popup: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/icon.png

  fonts:
    - family: cairo
      fonts:
        - asset: fonts\CAIRO-REGULAR.TTF
    - family: mont
      fonts:
        - asset: fonts\MONTSERRAT-REGULAR.OTF
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
